# setup-env.ps1
# Run this once locally to create your .env file
# Usage: .\setup-env.ps1

$envFile = "C:\Users\TGNE\Desktop\newbot\.env"

if (Test-Path $envFile) {
    Write-Host "⚠️  .env already exists. Delete it first if you want to recreate." -ForegroundColor Yellow
    exit
}

$dbUrl    = Read-Host "Paste your Neon DATABASE_URL"
$bizName  = Read-Host "Business name (e.g. My Business Ghana)"
$phone    = Read-Host "Your WhatsApp number digits only (e.g. 233241234567)"
$password = Read-Host "Admin dashboard password"
$grokKey  = Read-Host "Grok API key (from console.x.ai) — press Enter to skip"

@"
# Auto-generated by setup-env.ps1
DATABASE_URL=$dbUrl
BUSINESS_NAME=$bizName
ADMIN_PHONE=$phone
ADMIN_PASSWORD=$password
ADMIN_USERNAME=admin
ADMIN_PORT=3001
ADMIN_SECRET=changeme123
GROK_API_KEY=$grokKey
GROK_MODEL=grok-3
SESSION_NAME=whatsapp-bot
SESSION_FOLDER=./tokens
DRIP_DAY1_HOURS=24
DRIP_DAY2_HOURS=48
DRIP_DAY3_HOURS=72
RATE_LIMIT_PER_HOUR=10
LOG_LEVEL=info
LOG_FILE=./logs/bot.log
"@ | Out-File -FilePath $envFile -Encoding utf8

Write-Host ""
Write-Host "✅ .env file created at $envFile" -ForegroundColor Green
Write-Host "   Now run: node src/index.js" -ForegroundColor Cyan
